require('core.plugin_config.color_theme')
require('core.plugin_config.completions')
require('core.plugin_config.gitsigns')
require('core.plugin_config.lualine')
require('core.plugin_config.oil')
require('core.plugin_config.telescope')
require('core.plugin_config.dashboard')
require('core.plugin_config.aerial')
