require('core.plugin_config.color_theme')
require('core.plugin_config.completions')
require('core.plugin_config.gitsigns')
require('core.plugin_config.plain')
require('core.plugin_config.oil')
require('core.plugin_config.telescope')
