require('core.plugin_config.color_theme')
require('core.plugin_config.completions')
require('core.plugin_config.dashboard')
require('core.plugin_config.gitsigns')
require('core.plugin_config.plain')
require('core.plugin_config.neo_tree')
require('core.plugin_config.telescope')
